server:
  port: 19103
  servlet:
    context-path: /

spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: ad12min
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery:
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          #          url: jdbc:mysql://47.97.123.235:3306/questiondb?characterEncoding=UTF-8&useUnicode=true&useSSL=false
          #          username: question
          #          password: question01
          url: jdbc:mysql://localhost:3306/tqmsn?characterEncoding=UTF-8&useUnicode=true&useSSL=false
#          url: jdbc:mysql://47.92.159.2:13307/tqmsn?characterEncoding=UTF-8&useUnicode=true&useSSL=false
#          url: jdbc:mysql://localhost:13307/tqmsn?characterEncoding=UTF-8&useUnicode=true&useSSL=false
#          username: tqmsn
          username: root
#          password: T9m5n@2022!
          password: 123456
#          password: tqms$2021@Shijiyunyi
          driver-class-name: com.mysql.jdbc.Driver



#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/qu/modules/**/xml/*Mapper.xml
  #日志中打印sql
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#token解析url
system:
  tokenUrl: http://csdemokszk.shijiyunyi.com/business/tbUser/currentInfo
#  tokenUrl: http://localhost:19101/business/tbUser/currentInfo
#  singleDiseaseReportUrl: http://drgs.0060.cn:80/interface/010102/%s/1.2/put/
  singleDiseaseReportUrl: http://192.168.1.23:80/interface/010102/%s/1.2/put/
#  writeMetabaseUrl: http://tqmszbservice.shijiyunyi.com/business/metadata/updateMetaData
  writeMetabaseUrl: http://localhost:19102/business/metadata/updateMetaData
